<?php

/**
 * Impliments hook_views_api()
 */
function commerce_unleashed_order_views_api() {
  return array(
    'api' => 3,
  );
}

function commerce_unleased_order_post($commerce_order) {
  $line_items = views_json_get('unleashed_line_item_json', 'default', $commerce_order->order_id);
  $order = views_json_get('unleashed_order_json', 'default', $commerce_order->order_id);

  $owner = user_load($commerce_order->uid);
  $order->Customer = new stdClass();
  $order->Customer->CustomerCode = $owner->name;
  $order->Customer->Guid = $owner->uuid;


  $order->SalesOrderLines = $line_items;

  $order->Tax = new stdClass();
  $order->Tax->TaxCode = 'None';

  watchdog('commerce_unleashed', '<pre>' . print_r($line_items, TRUE) . '</pre>');
  watchdog('commerce_unleashed', '<pre>' . print_r($order, TRUE) . '</pre>');

  $endpoint = '/SalesInvoices/';
  $responce = commerce_unleashed_post_json($endpoint, $commerce_order->uuid, $order);

  watchdog('commerce_unleashed', '<pre>' . print_r($responce, TRUE) . '</pre>');
}
