<?php

/**
 * @file
 * Main file.
 */

use Drupal\commerce_cart\Form\AddToCartFormInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_cron().
 */
function commerce_unleashed_cron(): void {
  $settings = Drupal::configFactory()->get('commerce_unleashed.settings');

  if ($settings->get('products.cron')) {
    $last_product_sync = Drupal::keyValue('commerce_unleashed')->get('products') ?? 0;
    $query = 'brief=true';
    if ($last_product_sync > 0) {
      $last_modified_date = date('Y-m-d', $last_product_sync);
      $query .= '&modifiedSince=' . $last_modified_date;
    }
    Drupal::service('commerce_unleashed.manager')->syncProducts($query);
    Drupal::keyValue('commerce_unleashed')->set('products', time());
  }

  if ($settings->get('stock.sync')) {
    $last_sync = Drupal::keyValue('commerce_unleashed')->get('stock_on_hand_sync') ?? 0;
    if ($last_sync < time() - 60 * 10) {
      Drupal::service('commerce_unleashed.manager')->syncStockOnHand();
      Drupal::keyValue('commerce_unleashed')->set('stock_on_hand_sync', time());
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for 'commerce_order_item_add_to_cart_form'.
 */
function commerce_unleashed_form_commerce_order_item_add_to_cart_form_alter(&$form, FormStateInterface $form_state): void {
  $form_object = $form_state->getFormObject();

  if ($form_object instanceof AddToCartFormInterface) {
    /** @var \Drupal\commerce_unleashed\UnleashedManagerInterface $unleashed_manager */
    $unleashed_manager = \Drupal::service('commerce_unleashed.manager');

    if ($unleashed_manager->enforceStockAvailability()) {
      // Get order item from the form.
      /** @var \Drupal\commerce_order\Entity\OrderItemInterface $order_item */
      $order_item = $form_object->getEntity();

      // Purchasable entity to be used in the form.
      if ($purchased_entity = $order_item->getPurchasedEntity()) {
        if ($unleashed_manager->getStockOnHand($purchased_entity) === 0) {
          $form['actions']['submit']['#disabled'] = TRUE;
          $form['actions']['submit']['#value'] = new TranslatableMarkup('Sold out');
        }
      }
    }
  }
}
