<?php

/**
 * @file
 * Main file.
 */


/**
 * Implements hook_cron().
 */
function commerce_unleashed_cron(): void {
  $settings = Drupal::configFactory()->get('commerce_unleashed.settings');

  if ($settings->get('products.cron')) {
    $last_product_sync = Drupal::keyValue('commerce_unleashed')->get('products') ?? 0;
    $query = 'brief=true';
    if ($last_product_sync > 0) {
      $last_modified_date = date('Y-m-d', $last_product_sync);
      $query .= '&modifiedSince=' . $last_modified_date;
    }
    Drupal::service('commerce_unleashed.manager')->syncProducts($query);
    Drupal::keyValue('commerce_unleashed')->set('products', time());
  }

  if ($settings->get('stock.sync')) {
    $last_sync = Drupal::keyValue('commerce_unleashed')->get('stock_on_hand_sync') ?? 0;
    if ($last_sync < time() - 60 * 10) {
      Drupal::service('commerce_unleashed.manager')->syncStockOnHand();
      Drupal::keyValue('commerce_unleashed')->set('stock_on_hand_sync', time());
    }
  }
}
