<?php

/**
 * Impliments hook_views_api()
 */
function commerce_unleashed_customer_views_api() {
  return array(
    'api' => 3,
  );
}

function commerce_unleased_customer_post($commerce_user) {
  $customer = views_json_get('unleashed_user_json', 'default', $commerce_user->uid);

  watchdog('commerce_unleashed', '<pre>' . print_r($customer, TRUE) . '</pre>');

  $endpoint = '/Customers/';
  $responce = commerce_unleashed_post_json($endpoint, $commerce_user->uuid, $customer);

  watchdog('commerce_unleashed', '<pre>' . print_r($responce, TRUE) . '</pre>');
}
